AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-large-payload-handler

  Sample SAM Template for lambda-large-payload-handler

Globals:
  Function:
    Timeout: 20

Resources:
  LargeMessageHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: LargeMessageHandler
      Handler: net.sailes.example.LargePayloadHandler::handleRequest
      Runtime: java8
      MemorySize: 512
      Policies:
        - S3CrudPolicy:
            BucketName: ms-extended-sqs-client
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt LargeMessagesQueue.Arn
            BatchSize: 10

  LargeMessagesQueue:
    Type: AWS::SQS::Queue
